"""Lightweight i18n for the backend (engine, executors, CLI).

No dependencies. Language is resolved from the ``BORSCHT_LANG`` env var, then the
``language`` setting, then ``en``. Machine tokens (status codes, verdicts, action
names, rule ids) stay canonical/English; only human-readable prose is localized.

Generated artifact/trace content is localized at creation time using the active
language, so each run records prose in the language it was created with.
"""

from __future__ import annotations

import os
from typing import Optional

SUPPORTED = ("en", "ru")
DEFAULT_LANG = "en"

_LANG = DEFAULT_LANG

MESSAGES = {
    "en": {
        # contract / steps
        "contract.text": "Workflow '{name}' (risk {risk}). Intended actions: {actions}. Owner {owner} holds the risk.",
        "actions.none": "none",
        "step.signal_received": "Signal received for workflow '{workflow}'.",
        "step.context_built": "Task contract built; {n} similar past run(s) recalled.",
        "step.policy_denied": "Policy denied execution.",
        "step.policy_approval": "Policy requires human approval before execution.",
        "step.policy_allow": "Policy allows execution.",
        "step.decision_go": "Verdict: GO.",
        "step.evidence_written": "{n} evidence artifact(s) written.",
        "step.approved": "Approved by {actor}. Verdict: GO.",
        "step.rejected": "Rejected by {actor}.",
        "step.held": "Run held for review.",
        "step.retry": "Retry requested.",
        "step.rollback": "Run rolled back.",
        # explanations
        "explain.denied_default": "Denied by policy.",
        "explain.approval_default": "Human approval required.",
        "explain.allowed": "Allowed by policy; executed automatically.",
        "explain.exec_failed": "Execution failed: {error}",
        "explain.waived": "Policy waived by {actor}. {reason}",
        # artifact bodies
        "body.run": "Run",
        "body.workflow": "Workflow",
        "body.signal": "Signal",
        "body.empty": "(empty)",
        "body.generated_by": "Generated by Borscht Public Edition.",
        "body.result": "Result",
        "rollback.title": "Rollback",
        "rollback.note": "Run **{id}** rolled back by {actor}.",
        # executors
        "exec.md_generated": "Generated markdown artifact ({n} chars).",
        "exec.json_exported": "Exported JSON payload.",
        "exec.http_fetched": "Fetched {url} (truncated 5k).",
        "exec.action_executed": "Executed {action} via simulated connector.",
        "exec.file_written": "Wrote {path}.",
        "exec.handoff": "Handed off to human operator.",
        "exec.handoff_title": "Manual handoff",
        "exec.handoff_body": "Manual task handed to a human.",
        "exec.action_title": "Action: {action}",
        # CLI prose
        "cli.run": "run",
        "cli.status": "status",
        "cli.verdict": "verdict",
        "cli.explanation": "explanation",
        "cli.no_runs": "(no runs)",
        "cli.error": "error",
        "cli.exported": "exported",
        "cli.effect": "effect",
        "cli.workflow_required": "workflow required",
        "cli.run_not_found": "run not found",
        "cli.initialized": "Initialized Borscht data at: {path}",
        "cli.templates_available": "Templates available: {items}",
        "cli.policy_packs": "Policy packs: {items}",
        "cli.installed_template": "installed template: {id}",
        "cli.trace_header": "Run {id} [{status}] verdict={verdict}",
        "cli.trace_meta": "Workflow: {workflow}  Owner: {owner}  Risk: {risk}",
        "cli.policy_label": "Policy:",
        "cli.eval_line": "Eval: {passed}/{total} passed ({rate}%)  blocking_failures={bf}  -> {rec}",
        # status labels (display only; codes stay canonical)
        "status.draft": "draft",
        "status.queued": "queued",
        "status.running": "running",
        "status.awaiting_approval": "awaiting approval",
        "status.blocked_by_policy": "blocked by policy",
        "status.succeeded": "succeeded",
        "status.failed": "failed",
        "status.rolled_back": "rolled back",
        "status.waived": "waived",
        # localized policy reasons (by rule id; fall back to pack reason)
        "policy.reason.p0-secret-exfil": "Signal references secrets/credentials; outbound handling is denied (P0).",
        "policy.reason.p0-destructive-action": "Destructive tool requested without sandbox; denied by default (P0).",
        "policy.reason.p1-external-publish": "Action publishes/sends externally; human approval required before execution.",
        "policy.reason.p1-spend-increase": "Spend increase / budget mutation requires human approval (P1).",
        "policy.reason.p1-data-mutation": "Data mutation action requires human approval (P1).",
        "policy.reason.p1-high-risk-run": "Run is classified P0/P1 risk; human approval required before execution.",
        "policy.reason.p2-internal-allow": "Low-risk internal draft/analysis/summary; allowed.",
    },
    "ru": {
        "contract.text": "Процесс «{name}» (риск {risk}). Намеченные действия: {actions}. Владелец риска: {owner}.",
        "actions.none": "нет",
        "step.signal_received": "Получен сигнал для процесса «{workflow}».",
        "step.context_built": "Сформирован контракт задачи; найдено похожих прошлых прогонов: {n}.",
        "step.policy_denied": "Политика запретила выполнение.",
        "step.policy_approval": "Политика требует подтверждения человеком перед выполнением.",
        "step.policy_allow": "Политика разрешает выполнение.",
        "step.decision_go": "Вердикт: GO.",
        "step.evidence_written": "Записано артефактов evidence: {n}.",
        "step.approved": "Подтверждено: {actor}. Вердикт: GO.",
        "step.rejected": "Отклонено: {actor}.",
        "step.held": "Прогон поставлен на удержание для проверки.",
        "step.retry": "Запрошен повтор.",
        "step.rollback": "Прогон откатан.",
        "explain.denied_default": "Запрещено политикой.",
        "explain.approval_default": "Требуется подтверждение человеком.",
        "explain.allowed": "Разрешено политикой; выполнено автоматически.",
        "explain.exec_failed": "Ошибка выполнения: {error}",
        "explain.waived": "Политика отменена ({actor}). {reason}",
        "body.run": "Прогон",
        "body.workflow": "Процесс",
        "body.signal": "Сигнал",
        "body.empty": "(пусто)",
        "body.generated_by": "Сгенерировано Borscht Public Edition.",
        "body.result": "Результат",
        "rollback.title": "Откат",
        "rollback.note": "Прогон **{id}** откатан пользователем {actor}.",
        "exec.md_generated": "Сгенерирован markdown-артефакт ({n} симв.).",
        "exec.json_exported": "Экспортирован JSON-payload.",
        "exec.http_fetched": "Загружено {url} (обрезано до 5k).",
        "exec.action_executed": "Действие {action} выполнено через симулированный коннектор.",
        "exec.file_written": "Записан файл {path}.",
        "exec.handoff": "Передано человеку-оператору.",
        "exec.handoff_title": "Передача человеку",
        "exec.handoff_body": "Задача передана человеку.",
        "exec.action_title": "Действие: {action}",
        "cli.run": "прогон",
        "cli.status": "статус",
        "cli.verdict": "вердикт",
        "cli.explanation": "пояснение",
        "cli.no_runs": "(прогонов нет)",
        "cli.error": "ошибка",
        "cli.exported": "экспортировано",
        "cli.effect": "эффект",
        "cli.workflow_required": "требуется указать процесс (workflow)",
        "cli.run_not_found": "прогон не найден",
        "cli.initialized": "Данные Borscht инициализированы в: {path}",
        "cli.templates_available": "Доступные шаблоны: {items}",
        "cli.policy_packs": "Пакеты политик: {items}",
        "cli.installed_template": "шаблон установлен: {id}",
        "cli.trace_header": "Прогон {id} [{status}] вердикт={verdict}",
        "cli.trace_meta": "Процесс: {workflow}  Владелец: {owner}  Риск: {risk}",
        "cli.policy_label": "Политика:",
        "cli.eval_line": "Eval: пройдено {passed}/{total} ({rate}%)  блокирующих_провалов={bf}  -> {rec}",
        "status.draft": "черновик",
        "status.queued": "в очереди",
        "status.running": "выполняется",
        "status.awaiting_approval": "ждёт подтверждения",
        "status.blocked_by_policy": "заблокировано политикой",
        "status.succeeded": "успешно",
        "status.failed": "ошибка",
        "status.rolled_back": "откатано",
        "status.waived": "политика отменена",
        "policy.reason.p0-secret-exfil": "Сигнал упоминает секреты/учётные данные; исходящая обработка запрещена (P0).",
        "policy.reason.p0-destructive-action": "Запрошен деструктивный инструмент без песочницы; запрещено по умолчанию (P0).",
        "policy.reason.p1-external-publish": "Действие публикует/отправляет наружу; нужно подтверждение человеком.",
        "policy.reason.p1-spend-increase": "Увеличение расходов/бюджета требует подтверждения человеком (P1).",
        "policy.reason.p1-data-mutation": "Изменение данных требует подтверждения человеком (P1).",
        "policy.reason.p1-high-risk-run": "Прогон классифицирован как риск P0/P1; нужно подтверждение человеком.",
        "policy.reason.p2-internal-allow": "Низкорисковый внутренний черновик/анализ/резюме; разрешено.",
    },
}


def resolve_lang() -> str:
    env = os.environ.get("BORSCHT_LANG", "").strip().lower()
    if env in SUPPORTED:
        return env
    try:
        from borscht import config
        lang = str(config.load_settings().get("language", "")).strip().lower()
        if lang in SUPPORTED:
            return lang
    except Exception:  # noqa: BLE001
        pass
    return DEFAULT_LANG


def set_lang(lang: Optional[str]) -> None:
    global _LANG
    if lang and lang.lower() in SUPPORTED:
        _LANG = lang.lower()
    else:
        _LANG = DEFAULT_LANG


def current_lang() -> str:
    return _LANG


def t(key: str, lang: Optional[str] = None, **kwargs) -> str:
    use = (lang or _LANG)
    table = MESSAGES.get(use) or MESSAGES[DEFAULT_LANG]
    template = table.get(key)
    if template is None:
        template = MESSAGES[DEFAULT_LANG].get(key, key)
    try:
        return template.format(**kwargs) if kwargs else template
    except (KeyError, IndexError):
        return template


def status_label(status: str, lang: Optional[str] = None) -> str:
    return t("status." + status, lang=lang)


def policy_reason(rule_id: str, fallback: str, lang: Optional[str] = None) -> str:
    use = (lang or _LANG)
    table = MESSAGES.get(use) or MESSAGES[DEFAULT_LANG]
    return table.get("policy.reason." + rule_id, fallback)
